#!/bin/bash
MAINFILE="459-A-18022990.c"
EXEFILE="459-A-18022990"
ANGELIXPRE=$ANGELIX_RUN
INPUT_NAME=heldout-input-pos
NEGINPUT_NAME=heldout-input-neg
OUTPUT_NAME=heldout-output-pos
NEGOUTPUT_NAME=heldout-output-neg
MY_NAME=my_output
rm -R $MY_NAME* &>/dev/null
run_test()
{
test_case="$1"
if ! `which time` -o time.out -f "(%es)" timeout -k 50s 50s $ANGELIXPRE ./$EXEFILE < $test_case | sed -e '/^$/d' -e 's/^[ \t]*//' > $MY_NAME$test_case; then
echo Sample test \#$test_case: Runtime Error`cat time.out`
echo ========================================
echo Sample Input \#$test_case
        cat $test_case
exit 2
else
if grep "Command" time.out; then 
 echo "ERROR";
 exit -1;
fi
	if diff --brief --ignore-trailing-space $MY_NAME$test_case $2; then
echo Sample test \#$test_case: Accepted`cat time.out`
exit 0
	else
echo Sample test \#$test_case: Wrong Answer`cat time.out`
echo ========================================
 echo Sample Input \#$test_case
 cat $test_case
echo ========================================
echo Sample Output \#$2
cat $2
echo ========================================
echo My Output \#$MY_NAMEtest_case
cat $MY_NAME$test_case
echo ========================================
fi
    fi
}
case $1 in

p1) run_test "$INPUT_NAME"5 "$OUTPUT_NAME"5 ;;
p2) run_test "$INPUT_NAME"13 "$OUTPUT_NAME"13 ;;
p3) run_test "$INPUT_NAME"16 "$OUTPUT_NAME"16 ;;
p4) run_test "$INPUT_NAME"20 "$OUTPUT_NAME"20 ;;
p5) run_test "$INPUT_NAME"21 "$OUTPUT_NAME"21 ;;
p6) run_test "$INPUT_NAME"22 "$OUTPUT_NAME"22 ;;
p7) run_test "$INPUT_NAME"25 "$OUTPUT_NAME"25 ;;
p8) run_test "$INPUT_NAME"26 "$OUTPUT_NAME"26 ;;
p9) run_test "$INPUT_NAME"27 "$OUTPUT_NAME"27 ;;
p10) run_test "$INPUT_NAME"32 "$OUTPUT_NAME"32 ;;
p11) run_test "$INPUT_NAME"33 "$OUTPUT_NAME"33 ;;
p12) run_test "$INPUT_NAME"35 "$OUTPUT_NAME"35 ;;
p13) run_test "$INPUT_NAME"36 "$OUTPUT_NAME"36 ;;
p14) run_test "$INPUT_NAME"45 "$OUTPUT_NAME"45 ;;
p15) run_test "$INPUT_NAME"53 "$OUTPUT_NAME"53 ;;
p16) run_test "$INPUT_NAME"55 "$OUTPUT_NAME"55 ;;
p17) run_test "$INPUT_NAME"60 "$OUTPUT_NAME"60 ;;
p18) run_test "$INPUT_NAME"61 "$OUTPUT_NAME"61 ;;
p19) run_test "$INPUT_NAME"62 "$OUTPUT_NAME"62 ;;
p20) run_test "$INPUT_NAME"64 "$OUTPUT_NAME"64 ;;
p21) run_test "$INPUT_NAME"67 "$OUTPUT_NAME"67 ;;
p22) run_test "$INPUT_NAME"68 "$OUTPUT_NAME"68 ;;
p23) run_test "$INPUT_NAME"71 "$OUTPUT_NAME"71 ;;
p24) run_test "$INPUT_NAME"72 "$OUTPUT_NAME"72 ;;
p25) run_test "$INPUT_NAME"73 "$OUTPUT_NAME"73 ;;
exit 1
esac
 exit 1