{'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810', 'id': '2810',
 'fileList': [
    {'id': 0, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270010_buggy.c',
     'result': [0, 0, 0, 0],
     'errLines': ['10', '14'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                          {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                                          {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                          {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                          {'id': 4, 'code': '    float a,b,area;', 'type': '还没完成', 'lineNum': 4},
                                          {'id': 5, 'code': '    scanf("%f %f",&a, &b);', 'type': '还没完成', 'lineNum': 5},
                                          {'id': 6, 'code': '    area=.5*a*b;', 'type': '还没完成', 'lineNum': 6},
                                          {'id': 7, 'code': '    if (area>0)', 'type': '还没完成', 'lineNum': 7},
                                          {'id': 8, 'code': '    {', 'type': '还没完成', 'lineNum': 8},
                                          {'id': 9,
                                                                                                     'code': '        printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                                                                     'type': '还没完成',
                                                                                                     'lineNum': 9},
                                          {'id': 10, 'code': '    }', 'type': '还没完成', 'lineNum': 10},
                                          {'id': 11, 'code': '    else', 'type': '还没完成', 'lineNum': 11},
                                          {'id': 12, 'code': '    {', 'type': '还没完成', 'lineNum': 12}, {'id': 13,
                                                                                                       'code': '        printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,-area);',
                                                                                                       'type': '还没完成',
                                                                                                       'lineNum': 13},
                                          {'id': 14, 'code': '    }', 'type': '还没完成', 'lineNum': 14},
                                          {'id': 15, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 15},
                                          {'id': 16, 'code': '}', 'type': '还没完成', 'lineNum': 16}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [1, 1, 1, 1], [0, 0, 0, 0], [1, 0, 1, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 1, 0, 1],
              [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0]],
     'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270010_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 17, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b,area;', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    scanf("%f %f",&a, &b);', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    area=.5*a*b;', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '    if (area>0)', 'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    {', 'type': '还没完成', 'lineNum': 8}, {'id': 9,
                                                                             'code': '        printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                                             'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '    }', 'type': '还没完成', 'lineNum': 10},
                  {'id': 11, 'code': '    else', 'type': '还没完成', 'lineNum': 11},
                  {'id': 12, 'code': '    {', 'type': '还没完成', 'lineNum': 12}, {'id': 13,
                                                                               'code': '        printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,-area);',
                                                                               'type': '还没完成', 'lineNum': 13},
                  {'id': 14, 'code': '    }', 'type': '还没完成', 'lineNum': 14},
                  {'id': 15, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 15},
                  {'id': 16, 'code': '}', 'type': '还没完成', 'lineNum': 16}]},
    {'id': 1, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270011_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['10', '14'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                          {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                                          {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                          {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                          {'id': 4, 'code': '    float a,b,area;', 'type': '还没完成', 'lineNum': 4},
                                          {'id': 5, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                                          {'id': 6, 'code': '    area = (a*b)/2;', 'type': '还没完成', 'lineNum': 6},
                                          {'id': 7, 'code': '    if(area>0)', 'type': '还没完成', 'lineNum': 7},
                                          {'id': 8, 'code': '    {', 'type': '还没完成', 'lineNum': 8},
                                          {'id': 9,
                                                                                                     'code': '        printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                                                                     'type': '还没完成',
                                                                                                     'lineNum': 9},
                                          {'id': 10, 'code': '    }', 'type': '还没完成', 'lineNum': 10},
                                          {'id': 11, 'code': '    else', 'type': '还没完成', 'lineNum': 11},
                                          {'id': 12, 'code': '    {', 'type': '还没完成', 'lineNum': 12},
                                          {'id': 13,'code': '        printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,(-1)*area);',
                                                                                                       'type': '还没完成',
                                                                                                       'lineNum': 13},
                                          {'id': 14, 'code': '    }', 'type': '还没完成', 'lineNum': 14},
                                          {'id': 15, 'code': '', 'type': '还没完成', 'lineNum': 15},
                                          {'id': 16, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 16},
                                          {'id': 17, 'code': '}', 'type': '还没完成', 'lineNum': 17}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [1, 1, 1, 1], [0, 0, 0, 0], [1, 0, 1, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 1, 0, 1],
              [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270011_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 18, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b,area;', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    area = (a*b)/2;', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '    if(area>0)', 'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    {', 'type': '还没完成', 'lineNum': 8}, {'id': 9,
                                                                             'code': '        printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                                             'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '    }', 'type': '还没完成', 'lineNum': 10},
                  {'id': 11, 'code': '    else', 'type': '还没完成', 'lineNum': 11},
                  {'id': 12, 'code': '    {', 'type': '还没完成', 'lineNum': 12}, {'id': 13,
                                                                               'code': '        printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,(-1)*area);',
                                                                               'type': '还没完成', 'lineNum': 13},
                  {'id': 14, 'code': '    }', 'type': '还没完成', 'lineNum': 14},
                  {'id': 15, 'code': '', 'type': '还没完成', 'lineNum': 15},
                  {'id': 16, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 16},
                  {'id': 17, 'code': '}', 'type': '还没完成', 'lineNum': 17}]},
    {'id': 2, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270022_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['13'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                    {'id': 1, 'code': '#include<math.h>', 'type': '还没完成', 'lineNum': 1},
                                    {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                    {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                    {'id': 4, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 4},
                                    {'id': 5, 'code': '    float area;', 'type': '还没完成', 'lineNum': 5},
                                    {'id': 6, 'code': '    scanf("%f",&a);', 'type': '还没完成', 'lineNum': 6},
                                    {'id': 7, 'code': '    printf(" ");', 'type': '还没完成', 'lineNum': 7},
                                    {'id': 8, 'code': '    scanf("%f",&b);', 'type': '还没完成', 'lineNum': 8},
                                    {'id': 9, 'code': '', 'type': '还没完成', 'lineNum': 9},
                                    {'id': 10, 'code': '    area=fabs(a*b/2);', 'type': '还没完成', 'lineNum': 10},
                                    {'id': 11, 'code': '', 'type': '还没完成', 'lineNum': 11}, {'id': 12,
                                                                                            'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f",a,b,a,b,area);',
                                                                                            'type': '还没完成',
                                                                                            'lineNum': 12},
                                    {'id': 13, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 13},
                                    {'id': 14, 'code': '}', 'type': '还没完成', 'lineNum': 14}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1],
              [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270022_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 15, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '#include<math.h>', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    float area;', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    scanf("%f",&a);', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '    printf(" ");', 'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    scanf("%f",&b);', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '    area=fabs(a*b/2);', 'type': '还没完成', 'lineNum': 10},
                  {'id': 11, 'code': '', 'type': '还没完成', 'lineNum': 11}, {'id': 12,
                                                                          'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f",a,b,a,b,area);',
                                                                          'type': '还没完成', 'lineNum': 12},
                  {'id': 13, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 13},
                  {'id': 14, 'code': '}', 'type': '还没完成', 'lineNum': 14}]},
    {'id': 3, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270025_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['12'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                    {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                                    {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                    {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                    {'id': 4, 'code': '    ', 'type': '还没完成', 'lineNum': 4},
                                    {'id': 5, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 5},
                                    {'id': 6, 'code': '', 'type': '还没完成', 'lineNum': 6},
                                    {'id': 7, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 7},
                                    {'id': 8, 'code': '    float height,base,aot;', 'type': '还没完成', 'lineNum': 8},
                                    {'id': 9, 'code': '    height=b;', 'type': '还没完成', 'lineNum': 9},
                                    {'id': 10, 'code': '    base=a;', 'type': '还没完成', 'lineNum': 10},
                                    {'id': 11, 'code': '    aot=1.0000/2*height*base;//area of triangle',
                                     'type': '还没完成', 'lineNum': 11}, {'id': 12,
                                                                      'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,aot);',
                                                                      'type': '还没完成', 'lineNum': 12},
                                    {'id': 13, 'code': '', 'type': '还没完成', 'lineNum': 13},
                                    {'id': 14, 'code': '', 'type': '还没完成', 'lineNum': 14},
                                    {'id': 15, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 15},
                                    {'id': 16, 'code': '}', 'type': '还没完成', 'lineNum': 16}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0],
              [1, 1, 1, 1], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0],
              [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270025_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 17, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    ', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    float height,base,aot;', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '    height=b;', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '    base=a;', 'type': '还没完成', 'lineNum': 10},
                  {'id': 11, 'code': '    aot=1.0000/2*height*base;//area of triangle', 'type': '还没完成', 'lineNum': 11},
                  {'id': 12,
                   'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,aot);',
                   'type': '还没完成', 'lineNum': 12}, {'id': 13, 'code': '', 'type': '还没完成', 'lineNum': 13},
                  {'id': 14, 'code': '', 'type': '还没完成', 'lineNum': 14},
                  {'id': 15, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 15},
                  {'id': 16, 'code': '}', 'type': '还没完成', 'lineNum': 16}]},
    {'id': 4, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270048_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['12'], 'lineId': [{'id': 0,
                                     'code': '//Welcome to C programming...Today, we have to calculate the area of the triangle formed by the three points (a,b), (a,0) and (0,b);',
                                     'type': '还没完成', 'lineNum': 0},
                                    {'id': 1, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 1},
                                    {'id': 2, 'code': '', 'type': '还没完成', 'lineNum': 2},
                                    {'id': 3, 'code': 'int main()', 'type': '还没完成', 'lineNum': 3},
                                    {'id': 4, 'code': '{', 'type': '还没完成', 'lineNum': 4},
                                    {'id': 5, 'code': '', 'type': '还没完成', 'lineNum': 5},
                                    {'id': 6, 'code': '', 'type': '还没完成', 'lineNum': 6},
                                    {'id': 7, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 7},
                                    {'id': 8, 'code': '', 'type': '还没完成', 'lineNum': 8}, {'id': 9,
                                                                                          'code': '    scanf("%f %f\\n",&a, &b);//It will take the input \'a\' & \'b\' from user',
                                                                                          'type': '还没完成', 'lineNum': 9},
                                    {'id': 10, 'code': '', 'type': '还没完成', 'lineNum': 10},
                                    {'id': 11, 'code': '    float c=0.5*a*b;//Will calculate the area of the triangle',
                                     'type': '还没完成', 'lineNum': 11},
                                    {'id': 12, 'code': '', 'type': '还没完成', 'lineNum': 12}, {'id': 13,
                                                                                            'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,c);',
                                                                                            'type': '还没完成',
                                                                                            'lineNum': 13},
                                    {'id': 14, 'code': '', 'type': '还没完成', 'lineNum': 14},
                                    {'id': 15, 'code': '', 'type': '还没完成', 'lineNum': 15},
                                    {'id': 16, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 16},
                                    {'id': 17, 'code': '}', 'type': '还没完成', 'lineNum': 17}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0],
              [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [1, 1, 1, 1],
              [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270048_buggy.c', 'id': 0, 'startLine': 4,
         'endLine': 18, 'name': 'int main()'}], 'codeList': [{'id': 0,
                                                              'code': '//Welcome to C programming...Today, we have to calculate the area of the triangle formed by the three points (a,b), (a,0) and (0,b);',
                                                              'type': '还没完成', 'lineNum': 0},
                                                             {'id': 1, 'code': '#include<stdio.h>', 'type': '还没完成',
                                                              'lineNum': 1},
                                                             {'id': 2, 'code': '', 'type': '还没完成', 'lineNum': 2},
                                                             {'id': 3, 'code': 'int main()', 'type': '还没完成',
                                                              'lineNum': 3},
                                                             {'id': 4, 'code': '{', 'type': '还没完成', 'lineNum': 4},
                                                             {'id': 5, 'code': '', 'type': '还没完成', 'lineNum': 5},
                                                             {'id': 6, 'code': '', 'type': '还没完成', 'lineNum': 6},
                                                             {'id': 7, 'code': '    float a,b;', 'type': '还没完成',
                                                              'lineNum': 7},
                                                             {'id': 8, 'code': '', 'type': '还没完成', 'lineNum': 8},
                                                             {'id': 9,
                                                              'code': '    scanf("%f %f\\n",&a, &b);//It will take the input \'a\' & \'b\' from user',
                                                              'type': '还没完成', 'lineNum': 9},
                                                             {'id': 10, 'code': '', 'type': '还没完成', 'lineNum': 10},
                                                             {'id': 11,
                                                              'code': '    float c=0.5*a*b;//Will calculate the area of the triangle',
                                                              'type': '还没完成', 'lineNum': 11},
                                                             {'id': 12, 'code': '', 'type': '还没完成', 'lineNum': 12},
                                                             {'id': 13,
                                                              'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,c);',
                                                              'type': '还没完成', 'lineNum': 13},
                                                             {'id': 14, 'code': '', 'type': '还没完成', 'lineNum': 14},
                                                             {'id': 15, 'code': '', 'type': '还没完成', 'lineNum': 15},
                                                             {'id': 16, 'code': '    return 0;', 'type': '还没完成',
                                                              'lineNum': 16},
                                                             {'id': 17, 'code': '}', 'type': '还没完成', 'lineNum': 17}]},
    {'id': 5, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270052_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['17'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                    {'id': 1, 'code': '#include<math.h>', 'type': '还没完成', 'lineNum': 1},
                                    {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                    {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                    {'id': 4, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 4},
                                    {'id': 5, 'code': '', 'type': '还没完成', 'lineNum': 5},
                                    {'id': 6, 'code': '    scanf("%f %f",&a,&b);', 'type': '还没完成', 'lineNum': 6},
                                    {'id': 7, 'code': '', 'type': '还没完成', 'lineNum': 7},
                                    {'id': 8, 'code': '    float area = (1.0/2.0)*a*b;', 'type': '还没完成', 'lineNum': 8},
                                    {'id': 9, 'code': '    if(area>0)', 'type': '还没完成', 'lineNum': 9},
                                    {'id': 10, 'code': '    {', 'type': '还没完成', 'lineNum': 10},
                                    {'id': 11, 'code': '', 'type': '还没完成', 'lineNum': 11}, {'id': 12,
                                                                                            'code': '        printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                                                            'type': '还没完成',
                                                                                            'lineNum': 12},
                                    {'id': 13, 'code': '    }', 'type': '还没完成', 'lineNum': 13},
                                    {'id': 14, 'code': '    else', 'type': '还没完成', 'lineNum': 14},
                                    {'id': 15, 'code': '    {', 'type': '还没完成', 'lineNum': 15}, {'id': 16,
                                                                                                 'code': '        printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f",a,b,a,b,-1*area);',
                                                                                                 'type': '还没完成',
                                                                                                 'lineNum': 16},
                                    {'id': 17, 'code': '    }', 'type': '还没完成', 'lineNum': 17},
                                    {'id': 18, 'code': '', 'type': '还没完成', 'lineNum': 18},
                                    {'id': 19, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 19},
                                    {'id': 20, 'code': '}', 'type': '还没完成', 'lineNum': 20}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1],
              [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 0, 1, 0], [0, 0, 0, 0],
              [0, 0, 0, 0], [0, 0, 0, 0], [0, 1, 0, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0]],
     'funList': [{'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270052_buggy.c', 'id': 0, 'startLine': 3,
                  'endLine': 21, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '#include<math.h>', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    scanf("%f %f",&a,&b);', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '', 'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    float area = (1.0/2.0)*a*b;', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '    if(area>0)', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '    {', 'type': '还没完成', 'lineNum': 10},
                  {'id': 11, 'code': '', 'type': '还没完成', 'lineNum': 11}, {'id': 12,
                                                                          'code': '        printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                                          'type': '还没完成', 'lineNum': 12},
                  {'id': 13, 'code': '    }', 'type': '还没完成', 'lineNum': 13},
                  {'id': 14, 'code': '    else', 'type': '还没完成', 'lineNum': 14},
                  {'id': 15, 'code': '    {', 'type': '还没完成', 'lineNum': 15}, {'id': 16,
                                                                               'code': '        printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f",a,b,a,b,-1*area);',
                                                                               'type': '还没完成', 'lineNum': 16},
                  {'id': 17, 'code': '    }', 'type': '还没完成', 'lineNum': 17},
                  {'id': 18, 'code': '', 'type': '还没完成', 'lineNum': 18},
                  {'id': 19, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 19},
                  {'id': 20, 'code': '}', 'type': '还没完成', 'lineNum': 20}]},
    {'id': 6, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270053_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['7'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                   {'id': 1, 'code': '#include<stdlib.h>', 'type': '还没完成', 'lineNum': 1},
                                   {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                   {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                   {'id': 4, 'code': '    float a,b,area;         //initialising the variables',
                                    'type': '还没完成', 'lineNum': 4},
                                   {'id': 5, 'code': '    scanf("%f %f",&a,&b);   //accepting values from user',
                                    'type': '还没完成', 'lineNum': 5},
                                   {'id': 6, 'code': '    area=0.5*abs(a)*abs(b);           //evaluating area',
                                    'type': '还没完成', 'lineNum': 6}, {'id': 7,
                                                                    'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);                             //printing',
                                                                    'type': '还没完成', 'lineNum': 7},
                                   {'id': 8, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 8},
                                   {'id': 9, 'code': '}', 'type': '还没完成', 'lineNum': 9}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270053_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 10, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '#include<stdlib.h>', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b,area;         //initialising the variables', 'type': '还没完成',
                   'lineNum': 4},
                  {'id': 5, 'code': '    scanf("%f %f",&a,&b);   //accepting values from user', 'type': '还没完成',
                   'lineNum': 5},
                  {'id': 6, 'code': '    area=0.5*abs(a)*abs(b);           //evaluating area', 'type': '还没完成',
                   'lineNum': 6}, {'id': 7,
                                   'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);                             //printing',
                                   'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '}', 'type': '还没完成', 'lineNum': 9}]},
    {'id': 7, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270054_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['12'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                    {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                                    {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                    {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                    {'id': 4, 'code': '    float a,b,s;', 'type': '还没完成', 'lineNum': 4},
                                    {'id': 5, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                                    {'id': 6, 'code': '    s=(1.0/2.0)*(a*b);', 'type': '还没完成', 'lineNum': 6},
                                    {'id': 7, 'code': '    if (s<0)', 'type': '还没完成', 'lineNum': 7},
                                    {'id': 8, 'code': '    {', 'type': '还没完成', 'lineNum': 8},
                                    {'id': 9, 'code': '        s=-1*(s);', 'type': '还没完成', 'lineNum': 9},
                                    {'id': 10, 'code': '    }', 'type': '还没完成', 'lineNum': 10}, {'id': 11,
                                                                                                 'code': '    printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,s);',
                                                                                                 'type': '还没完成',
                                                                                                 'lineNum': 11},
                                    {'id': 12, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 12},
                                    {'id': 13, 'code': '}', 'type': '还没完成', 'lineNum': 13}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [1, 1, 1, 1], [0, 0, 0, 0], [0, 1, 0, 1], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0]],
     'funList': [{'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270054_buggy.c', 'id': 0, 'startLine': 3,
                  'endLine': 14, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b,s;', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    s=(1.0/2.0)*(a*b);', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '    if (s<0)', 'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    {', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '        s=-1*(s);', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '    }', 'type': '还没完成', 'lineNum': 10},
                  {'id': 11, 'code': '    printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,s);',
                   'type': '还没完成', 'lineNum': 11}, {'id': 12, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 12},
                  {'id': 13, 'code': '}', 'type': '还没完成', 'lineNum': 13}]},
    {'id': 8, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270057_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['7'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                   {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                                   {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                   {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                   {'id': 4, 'code': '    float a,b,area;    //variable initiation', 'type': '还没完成',
                                    'lineNum': 4},
                                   {'id': 5, 'code': '    scanf("%f %f",&a,&b);     //input of a,b', 'type': '还没完成',
                                    'lineNum': 5},
                                   {'id': 6, 'code': '    area=a*b/2;          //calculating area', 'type': '还没完成',
                                    'lineNum': 6}, {'id': 7,
                                                    'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                    'type': '还没完成', 'lineNum': 7},
                                   {'id': 8, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 8},
                                   {'id': 9, 'code': '}', 'type': '还没完成', 'lineNum': 9}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270057_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 10, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b,area;    //variable initiation', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    scanf("%f %f",&a,&b);     //input of a,b', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    area=a*b/2;          //calculating area', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7,
                   'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                   'type': '还没完成', 'lineNum': 7}, {'id': 8, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '}', 'type': '还没完成', 'lineNum': 9}]},
    {'id': 9, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270068_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['7'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0}, {'id': 1,
                                                                                                          'code': '#include<stdlib.h>        // this header file includes the abs() function ',
                                                                                                          'type': '还没完成',
                                                                                                          'lineNum': 1},
                                   {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                   {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                   {'id': 4, 'code': '    float a,b,area ;      ', 'type': '还没完成', 'lineNum': 4},
                                   {'id': 5, 'code': '    scanf("%f %f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                                   {'id': 6, 'code': '    area = 0.5*abs(a)*abs(b); ', 'type': '还没完成', 'lineNum': 6},
                                   {'id': 7,
                                    'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                    'type': '还没完成', 'lineNum': 7},
                                   {'id': 8, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 8},
                                   {'id': 9, 'code': '}', 'type': '还没完成', 'lineNum': 9}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270068_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 10, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '#include<stdlib.h>        // this header file includes the abs() function ',
                   'type': '还没完成', 'lineNum': 1}, {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b,area ;      ', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    scanf("%f %f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    area = 0.5*abs(a)*abs(b); ', 'type': '还没完成', 'lineNum': 6}, {'id': 7,
                                                                                                      'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                                                                      'type': '还没完成',
                                                                                                      'lineNum': 7},
                  {'id': 8, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '}', 'type': '还没完成', 'lineNum': 9}]},
    {'id': 10, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270081_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['12', '16'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                          {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                                          {'id': 2, 'code': 'int main()                   ', 'type': '还没完成',
                                           'lineNum': 2}, {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                          {'id': 4, 'code': '    float a;', 'type': '还没完成', 'lineNum': 4},
                                          {'id': 5, 'code': '    float b;', 'type': '还没完成', 'lineNum': 5},
                                          {'id': 6, 'code': '    scanf("%f%f", &a, &b); ', 'type': '还没完成',
                                           'lineNum': 6},
                                          {'id': 7, 'code': '    float area;', 'type': '还没完成', 'lineNum': 7},
                                          {'id': 8, 'code': '    area = (a*b)/2;        ', 'type': '还没完成',
                                           'lineNum': 8},
                                          {'id': 9, 'code': '    if (area >= 0)         ', 'type': '还没完成',
                                           'lineNum': 9}, {'id': 10, 'code': '    {', 'type': '还没完成', 'lineNum': 10},
                                          {'id': 11,
                                           'code': '        printf("The area of (%6.4f, %6.4f), (%6.4f,0) and (0,%6.4f) is %6.4f.", a, b, a, b, area);',
                                           'type': '还没完成', 'lineNum': 11},
                                          {'id': 12, 'code': '    }', 'type': '还没完成', 'lineNum': 12},
                                          {'id': 13, 'code': '    else', 'type': '还没完成', 'lineNum': 13},
                                          {'id': 14, 'code': '    {', 'type': '还没完成', 'lineNum': 14}, {'id': 15,
                                                                                                       'code': '        printf("The area of (%6.4f, %6.4f), (%6.4f,0) and (0,%6.4f) is %6.4f.", a, b, a, b, area-(area*2));',
                                                                                                       'type': '还没完成',
                                                                                                       'lineNum': 15},
                                          {'id': 16, 'code': '    }                       ', 'type': '还没完成',
                                           'lineNum': 16},
                                          {'id': 17, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 17},
                                          {'id': 18, 'code': '}', 'type': '还没完成', 'lineNum': 18}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1],
              [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0], [1, 0, 1, 0], [0, 0, 0, 0], [0, 0, 0, 0],
              [0, 0, 0, 0], [0, 1, 0, 1], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270081_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 19, 'name': 'int main()                   '}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()                   ', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a;', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    float b;', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    scanf("%f%f", &a, &b); ', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '    float area;', 'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    area = (a*b)/2;        ', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '    if (area >= 0)         ', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '    {', 'type': '还没完成', 'lineNum': 10}, {'id': 11,
                                                                               'code': '        printf("The area of (%6.4f, %6.4f), (%6.4f,0) and (0,%6.4f) is %6.4f.", a, b, a, b, area);',
                                                                               'type': '还没完成', 'lineNum': 11},
                  {'id': 12, 'code': '    }', 'type': '还没完成', 'lineNum': 12},
                  {'id': 13, 'code': '    else', 'type': '还没完成', 'lineNum': 13},
                  {'id': 14, 'code': '    {', 'type': '还没完成', 'lineNum': 14}, {'id': 15,
                                                                               'code': '        printf("The area of (%6.4f, %6.4f), (%6.4f,0) and (0,%6.4f) is %6.4f.", a, b, a, b, area-(area*2));',
                                                                               'type': '还没完成', 'lineNum': 15},
                  {'id': 16, 'code': '    }                       ', 'type': '还没完成', 'lineNum': 16},
                  {'id': 17, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 17},
                  {'id': 18, 'code': '}', 'type': '还没完成', 'lineNum': 18}]},
    {'id': 11, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270083_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['8'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                   {'id': 1, 'code': '#include<math.h>', 'type': '还没完成', 'lineNum': 1},
                                   {'id': 2, 'code': '', 'type': '还没完成', 'lineNum': 2},
                                   {'id': 3, 'code': 'int main()', 'type': '还没完成', 'lineNum': 3},
                                   {'id': 4, 'code': '{', 'type': '还没完成', 'lineNum': 4},
                                   {'id': 5, 'code': '    float a,b,area;', 'type': '还没完成', 'lineNum': 5},
                                   {'id': 6, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 6},
                                   {'id': 7, 'code': '    area=abs(0.5*a*b);', 'type': '还没完成', 'lineNum': 7}, {'id': 8,
                                                                                                               'code': '    printf("The area of (%6.4f,%6.4f), (%6.4f,0) and (0,%6.4f) is %6.4f.",a,b,a,b,area);',
                                                                                                               'type': '还没完成',
                                                                                                               'lineNum': 8},
                                   {'id': 9, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 9},
                                   {'id': 10, 'code': '}', 'type': '还没完成', 'lineNum': 10}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1],
              [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270083_buggy.c', 'id': 0, 'startLine': 4,
         'endLine': 11, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '#include<math.h>', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': '', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': 'int main()', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '{', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    float a,b,area;', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '    area=abs(0.5*a*b);', 'type': '还没完成', 'lineNum': 7}, {'id': 8,
                                                                                              'code': '    printf("The area of (%6.4f,%6.4f), (%6.4f,0) and (0,%6.4f) is %6.4f.",a,b,a,b,area);',
                                                                                              'type': '还没完成',
                                                                                              'lineNum': 8},
                  {'id': 9, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '}', 'type': '还没完成', 'lineNum': 10}]},
    {'id': 12, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270084_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['12'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                    {'id': 1, 'code': 'int main()', 'type': '还没完成', 'lineNum': 1},
                                    {'id': 2, 'code': '{', 'type': '还没完成', 'lineNum': 2},
                                    {'id': 3, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 3},
                                    {'id': 4, 'code': '    //taking input from user', 'type': '还没完成', 'lineNum': 4},
                                    {'id': 5, 'code': '    scanf("%f %f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                                    {'id': 6,
                                     'code': '    float area=(1.0/2)*a*b; //Area Of Right Triangle is 1/2*base*height',
                                     'type': '还没完成', 'lineNum': 6},
                                    {'id': 7, 'code': '    if (area<0)', 'type': '还没完成', 'lineNum': 7},
                                    {'id': 8, 'code': '    {', 'type': '还没完成', 'lineNum': 8},
                                    {'id': 9, 'code': '        area=-area;', 'type': '还没完成', 'lineNum': 9},
                                    {'id': 10, 'code': '    }', 'type': '还没完成', 'lineNum': 10}, {'id': 11,
                                                                                                 'code': '    printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                                                                 'type': '还没完成',
                                                                                                 'lineNum': 11},
                                    {'id': 12, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 12},
                                    {'id': 13, 'code': '}', 'type': '还没完成', 'lineNum': 13}],
     'maxi': [[0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [1, 1, 1, 1], [0, 0, 0, 0], [0, 1, 0, 1], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0]],
     'funList': [{'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270084_buggy.c', 'id': 0, 'startLine': 2,
                  'endLine': 14, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': 'int main()', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': '{', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    //taking input from user', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    scanf("%f %f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    float area=(1.0/2)*a*b; //Area Of Right Triangle is 1/2*base*height',
                   'type': '还没完成', 'lineNum': 6}, {'id': 7, 'code': '    if (area<0)', 'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    {', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '        area=-area;', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '    }', 'type': '还没完成', 'lineNum': 10}, {'id': 11,
                                                                               'code': '    printf("The area of (%.4f,%.4f),(%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,area);',
                                                                               'type': '还没完成', 'lineNum': 11},
                  {'id': 12, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 12},
                  {'id': 13, 'code': '}', 'type': '还没完成', 'lineNum': 13}]},
    {'id': 13, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270090_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['9'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                   {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                                   {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                   {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                   {'id': 4, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 4},
                                   {'id': 5, 'code': '    scanf("%f %f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                                   {'id': 6, 'code': '    float area=(1/2.0)*a*b;', 'type': '还没完成', 'lineNum': 6},
                                   {'id': 7, 'code': '    float ar=(-1/2.0)*a*b;', 'type': '还没完成', 'lineNum': 7},
                                   {'id': 8, 'code': '    printf("The area of (%.4f,%.4f),",a,b);', 'type': '还没完成',
                                    'lineNum': 8},
                                   {'id': 9, 'code': '    printf("(%.4f,0) and ",a);', 'type': '还没完成', 'lineNum': 9},
                                   {'id': 10, 'code': '    if (area>0)', 'type': '还没完成', 'lineNum': 10},
                                   {'id': 11, 'code': '    {', 'type': '还没完成', 'lineNum': 11},
                                   {'id': 12, 'code': '        printf("(0,%.4f) is %.4f.",b,area);', 'type': '还没完成',
                                    'lineNum': 12}, {'id': 13, 'code': '    }', 'type': '还没完成', 'lineNum': 13},
                                   {'id': 14, 'code': '    else', 'type': '还没完成', 'lineNum': 14},
                                   {'id': 15, 'code': '    {', 'type': '还没完成', 'lineNum': 15},
                                   {'id': 16, 'code': '        printf("(0,%.4f) is %.4f.",b,ar);', 'type': '还没完成',
                                    'lineNum': 16}, {'id': 17, 'code': '    }', 'type': '还没完成', 'lineNum': 17},
                                   {'id': 18, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 18},
                                   {'id': 19, 'code': '}', 'type': '还没完成', 'lineNum': 19}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0], [1, 0, 1, 0], [0, 0, 0, 0],
              [0, 0, 0, 0], [0, 0, 0, 0], [0, 1, 0, 1], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270090_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 20, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    scanf("%f %f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    float area=(1/2.0)*a*b;', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '    float ar=(-1/2.0)*a*b;', 'type': '还没完成', 'lineNum': 7},
                  {'id': 8, 'code': '    printf("The area of (%.4f,%.4f),",a,b);', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '    printf("(%.4f,0) and ",a);', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '    if (area>0)', 'type': '还没完成', 'lineNum': 10},
                  {'id': 11, 'code': '    {', 'type': '还没完成', 'lineNum': 11},
                  {'id': 12, 'code': '        printf("(0,%.4f) is %.4f.",b,area);', 'type': '还没完成', 'lineNum': 12},
                  {'id': 13, 'code': '    }', 'type': '还没完成', 'lineNum': 13},
                  {'id': 14, 'code': '    else', 'type': '还没完成', 'lineNum': 14},
                  {'id': 15, 'code': '    {', 'type': '还没完成', 'lineNum': 15},
                  {'id': 16, 'code': '        printf("(0,%.4f) is %.4f.",b,ar);', 'type': '还没完成', 'lineNum': 16},
                  {'id': 17, 'code': '    }', 'type': '还没完成', 'lineNum': 17},
                  {'id': 18, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 18},
                  {'id': 19, 'code': '}', 'type': '还没完成', 'lineNum': 19}]},
    {'id': 14, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270100_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['9'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                   {'id': 1, 'code': '#include<math.h>                   //to use fabs function.',
                                    'type': '还没完成', 'lineNum': 1}, {'id': 2, 'code': '', 'type': '还没完成', 'lineNum': 2},
                                   {'id': 3, 'code': 'int main()', 'type': '还没完成', 'lineNum': 3},
                                   {'id': 4, 'code': '{', 'type': '还没完成', 'lineNum': 4}, {'id': 5,
                                                                                          'code': '    float a,b,area;              //declaring variables to take input.',
                                                                                          'type': '还没完成', 'lineNum': 5},
                                   {'id': 6, 'code': '    scanf("%f%f",&a,&b);         //values being enterred.',
                                    'type': '还没完成', 'lineNum': 6}, {'id': 7,
                                                                    'code': '    area=fabs(0.5*a*b);          //area of right angled triangle=0.5*base                                  *height.',
                                                                    'type': '还没完成', 'lineNum': 7}, {'id': 8,
                                                                                                    'code': '    printf("The area of (% .4f,%.4f), (% .4f,0) and (0,%.4f) is %                  .4f.",a,b,a,b,area);   //printing the output.',
                                                                                                    'type': '还没完成',
                                                                                                    'lineNum': 8},
                                   {'id': 9, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 9},
                                   {'id': 10, 'code': '}', 'type': '还没完成', 'lineNum': 10}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1],
              [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270100_buggy.c', 'id': 0, 'startLine': 4,
         'endLine': 11, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '#include<math.h>                   //to use fabs function.', 'type': '还没完成',
                   'lineNum': 1}, {'id': 2, 'code': '', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': 'int main()', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '{', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    float a,b,area;              //declaring variables to take input.',
                   'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    scanf("%f%f",&a,&b);         //values being enterred.', 'type': '还没完成',
                   'lineNum': 6}, {'id': 7,
                                   'code': '    area=fabs(0.5*a*b);          //area of right angled triangle=0.5*base                                  *height.',
                                   'type': '还没完成', 'lineNum': 7}, {'id': 8,
                                                                   'code': '    printf("The area of (% .4f,%.4f), (% .4f,0) and (0,%.4f) is %                  .4f.",a,b,a,b,area);   //printing the output.',
                                                                   'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '}', 'type': '还没完成', 'lineNum': 10}]},
    {'id': 15, 'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270104_buggy.c', 'result': [0, 0, 0, 0],
     'errLines': ['7'], 'lineId': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                                   {'id': 1, 'code': '#include<math.h>', 'type': '还没完成', 'lineNum': 1},
                                   {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                                   {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                                   {'id': 4, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 4},
                                   {'id': 5, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                                   {'id': 6, 'code': '    float x = (1.0/2.0)*abs(a)*abs(b);', 'type': '还没完成',
                                    'lineNum': 6}, {'id': 7,
                                                    'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,x);',
                                                    'type': '还没完成', 'lineNum': 7},
                                   {'id': 8, 'code': '', 'type': '还没完成', 'lineNum': 8},
                                   {'id': 9, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 9},
                                   {'id': 10, 'code': '}', 'type': '还没完成', 'lineNum': 10}],
     'maxi': [[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1],
              [1, 1, 1, 1], [0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0]], 'funList': [
        {'pwd': '/home/zhangzhanwen/transtoGraceInput/ITSP-data/2810/270104_buggy.c', 'id': 0, 'startLine': 3,
         'endLine': 11, 'name': 'int main()'}],
     'codeList': [{'id': 0, 'code': '#include<stdio.h>', 'type': '还没完成', 'lineNum': 0},
                  {'id': 1, 'code': '#include<math.h>', 'type': '还没完成', 'lineNum': 1},
                  {'id': 2, 'code': 'int main()', 'type': '还没完成', 'lineNum': 2},
                  {'id': 3, 'code': '{', 'type': '还没完成', 'lineNum': 3},
                  {'id': 4, 'code': '    float a,b;', 'type': '还没完成', 'lineNum': 4},
                  {'id': 5, 'code': '    scanf("%f%f",&a,&b);', 'type': '还没完成', 'lineNum': 5},
                  {'id': 6, 'code': '    float x = (1.0/2.0)*abs(a)*abs(b);', 'type': '还没完成', 'lineNum': 6},
                  {'id': 7, 'code': '    printf("The area of (%.4f,%.4f), (%.4f,0) and (0,%.4f) is %.4f.",a,b,a,b,x);',
                   'type': '还没完成', 'lineNum': 7}, {'id': 8, 'code': '', 'type': '还没完成', 'lineNum': 8},
                  {'id': 9, 'code': '    return 0;', 'type': '还没完成', 'lineNum': 9},
                  {'id': 10, 'code': '}', 'type': '还没完成', 'lineNum': 10}]}],
 'inList': ['2810.1.in', '2810.2.in', '2810.3.in', '2810.4.in'],
 'fileId': ['270010_buggy.c', '270011_buggy.c', '270022_buggy.c', '270025_buggy.c', '270048_buggy.c', '270052_buggy.c',
            '270053_buggy.c', '270054_buggy.c', '270057_buggy.c', '270068_buggy.c', '270081_buggy.c', '270083_buggy.c',
            '270084_buggy.c', '270090_buggy.c', '270100_buggy.c', '270104_buggy.c']}
